name = "repeat_devlp"
uuid = "6f4aea17-c736-44cb-910f-e0713996749e"
authors = ["Gudongyangg"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
